import { Seal } from "./seal";

export const SEALS: Seal[] = [
    { id: 1, name: 'Harbour Seal' },
    { id: 2, name: 'Hooded Seal' },
    { id: 3, name: 'Bearded Seal' },
    { id: 4, name: 'Grey Seal' },
    { id: 5, name: 'Ribbon Seal' },
    { id: 6, name: 'Caspian Seal' },
    { id: 7, name: 'Harp Seal' },
    { id: 8, name: 'Ringed Seal' },
    { id: 9, name: 'Spotted Seal' },
    { id: 10, name: 'Baikal Seal' },
    { id: 11, name: 'Leopard Seal' },
    { id: 12, name: 'Weddell Seal' },
    { id: 13, name: 'Crabeater Seal' },
    { id: 14, name: 'Southern Elephant Seal' },
    { id: 15, name: 'Northern Elephant Seal' },
    { id: 16, name: 'Mediterranean Monk Seal' },
    { id: 17, name: 'Ross Seal' },
    { id: 18, name: 'Hawaiian Monk Seal' },
    { id: 19, name: 'Steller Sea Lion' },
    { id: 20, name: 'Australian Sea Lion' },
    { id: 21, name: 'South American Sea Lion' },
    { id: 22, name: 'New Zealand Sea Lion' },
    { id: 23, name: 'California, Galapagos and Japanese Sea Lions' },
    { id: 24, name: 'South American Fur Seal' },
    { id: 25, name: 'New Zealand Fur Seal' },
    { id: 26, name: 'Galapagos Fur Seal' },
    { id: 27, name: 'Antarctic Fur Seal' },
    { id: 28, name: 'Juan Fernandez Fur Seal' },
    { id: 29, name: 'South African and Australian Fur Seals' },
    { id: 30, name: 'Guadalupe Fur Seal' },
    { id: 31, name: 'Subantarctic Fur Seal' },
    { id: 32, name: 'Northern Fur Seal' }
];
